StduyWala/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import signup_page, login_page, home, logout_view, activate_account_page

app_name = 'accounts'

urlpatterns = [
    # Auth routes
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', activate_account_page, name='activate'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),

    # Password Reset routes
    path('accounts/reset-password/', auth_views.PasswordResetView.as_view(
    template_name='accounts/password_reset_form.html',
    email_template_name='accounts/password_reset_email.html',
    subject_template_name='accounts/password_reset_subject.txt',
    success_url=reverse_lazy('accounts:password_reset_done')
), name='reset_password'),


    path('accounts/reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),

    path('accounts/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),

    # Home route
    path('', home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_staff=False, is_admin=False, is_active=True): # may look repetitive adding staff, admin and active status, but it simplifies the
                                                                                        # work when using create_staffuser() and create_superuser()
        if not email:
            raise ValueError("User must have an email address")
        if not password:
            raise ValueError('User must have a password')
        user_obj = self.model(email=self.normalize_email(email))
        user_obj.set_password(password)
        user_obj.is_active = is_active
        user_obj.admin = is_admin
        user_obj.staff = is_staff
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True, is_admin=True)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'  # this now over rides the username field and now email is the default field
    # REQUIRED_FIELDS = [] if you add another field and need it to be required, include it in the list

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    """@property
    def is_active(self):
        return self.is_active"""

# keep the base user as simple as possible and only include the minimum basic required fields
# you can extend this user using a profile to get more info about your users. e.g.

#class Profile(models.Model):
    #user = models.OneToOneField(User)
    # then add some other fields e.g. first name, last name, phone number e.t.c.


class LoginAttempt(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    login_attempts = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'user: {}, attempts: {}'.format(self.user.email, self.login_attempts)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self): # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save he proovided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    ''' A form for updating users, includes all the fields on the user, but
    replaces the password fields with admin's password hash display field. '''

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'admin')

    def clean_password(self):
        ''' Regardless of what the user provides retrun the initial value.
        This is done here rather than on the field, because the field does
        not have access to the initial value. '''
        return self.initial['password']


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input',
                                                                           'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                                   'placeholder': 'Enter password'}))


class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['email']
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = False
            user.save()
        return user

accounts/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from .forms import RegistrationForm, LoginForm
from .models import LoginAttempt, User
from .token import account_activation_token
from .decorators import unauthenticated_user
from .utils import send_user_email


@unauthenticated_user
def signup_page(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            to_email = form.cleaned_data.get('email')
            current_site = get_current_site(request)
            mail_subject = 'Activate your account'
            response = send_user_email(user, mail_subject, to_email, current_site, 'accounts/email_verification.html')
            if response == 'success':
                messages.success(request, "We have sent you an activation link in your email. Please confirm your"
                                          "email to continue. Check your spam folder if you don't receive it")
            else:
                messages.error(request, 'An error occurred. Please ensure you have good internet connection and you have entered a valid email address')
                user.delete()
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm()

    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


@unauthenticated_user
def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            now = timezone.now()
            try:
                _user = User.objects.get(email=email)
                login_attempt, created = LoginAttempt.objects.get_or_create(user=_user)  # get the user's login attempt
                if (login_attempt.timestamp + timedelta(seconds=settings.LOGIN_ATTEMPTS_TIME_LIMIT)) < now:
                    user = authenticate(request, username=email, password=password)
                    if user is not None:
                        login(request, user)
                        login_attempt.login_attempts = 0    # reset the login attempts
                        login_attempt.save()
                        return redirect(settings.LOGIN_REDIRECT_URL)  # change expected_url in your project

                    else:
                        # if the password is incorrect, increment the login attempts and
                        # if the login attempts == MAX_LOGIN_ATTEMPTS, set the user to be inactive and send activation email
                        login_attempt.login_attempts += 1
                        login_attempt.timestamp = now
                        login_attempt.save()
                        if login_attempt.login_attempts == settings.MAX_LOGIN_ATTEMPTS:
                            _user.is_active = False
                            _user.save()
                            # send the re-activation email
                            mail_subject = "Account suspended"
                            current_site = get_current_site(request)
                            send_user_email(_user, mail_subject, email, current_site, 'accounts/email_account_suspended.html')
                            messages.error(request, 'Account suspended, maximum login attempts exceeded. '
                                                    'Reactivation link has been sent to your email')
                        else:
                            messages.error(request, 'Incorrect email or password')
                        return redirect(settings.LOGIN_URL)
                else:
                    messages.error(request, 'Login failed, please try again')
                    return redirect(settings.LOGIN_URL)

            except ObjectDoesNotExist:
                messages.error(request, 'Incorrect email or password')
                return redirect(settings.LOGIN_URL)
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def activate_account_page(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login_attempt, created = LoginAttempt.objects.get_or_create(user=user)
        if login_attempt.login_attempts >= settings.MAX_LOGIN_ATTEMPTS:
            login_attempt.login_attempts = 0
            login_attempt.save()
            messages.success(request, 'Account restored, you can now proceed to login')
        else:
            messages.success(request, 'Thank you for confirming your email. You can now login.')
        return redirect(settings.LOGIN_URL)
    else:
        messages.error(request, 'Activation link is invalid!')
        return redirect(settings.LOGIN_URL)


def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


""" 
    This is a dummy login view
    remove it from this app and use your own homeview
"""

@login_required
def home(request):
    return render(request, 'index.html')

templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Custom User Auth system</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Vendor CSS Files -->
  <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <div class="main">

        {% block content %}

        <!-- signup and login forms go here -->

        {% endblock content %}

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/accounts/email_account_suspended.html
{% autoescape off %}
Hi {{ user.username }},
We have detected suspicious activity on your account. Maximum login attempts
have been exceeded, as a result your account has been suspended.

Click the link below to reactivate your account.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/email_verification.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                <h2 class="form-title">Sign In</h2>
                {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
                {% endfor %}
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Sign In"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

            <p class="loginhere">
                Don't have an account ? <a href="{% url 'accounts:signup' %}" class="loginhere-link">Sign Up here</a>
            </p>
            <p class="loginhere">
                Forgot Password ? <a href="{% url 'accounts:reset_password' %}" class="loginhere-link">Reset Password</a>
            </p>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts/messages.html
      <div class="col-md-12">
        {% if messages %}
          {% for message in messages %}
             {% if message.tags == 'success' %}
                <div class="alert alert-success alert-with-icon">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
                  <span data-notify="icon" class="tim-icons icon-bell-55"></span>
                  <span data-notify="message">{{ message }}</span>
                </div>
             {% else %}
                <div class="alert alert-warning alert-with-icon">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
                  <span data-notify="icon" class="tim-icons icon-alert-circle-exc"></span>
                  <span data-notify="message">{{ message }}</span>
                </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>

templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                <h2 class="form-title">Password Reset</h2>
                <div class="mb-3">
                    {{ form|crispy }}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Send Reset Email"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

            <p class="loginhere">
                Don't have an account ? <a href="{% url 'accounts:signup' %}" class="loginhere-link">Sign Up here</a>
            </p>
            <p class="loginhere">
                Have already an account ? <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}

{% block content %}
  <div class="container">
    <h2>Password Reset Complete</h2>
    <p>Your password has been successfully reset. You can now log in with your new password.</p>
    <a href="{% url 'accounts:login' %}">Go to Login</a>
  </div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}

{% block content %}
  <div class="container">
    <h2>Reset Your Password</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change my password</button>
    </form>
  </div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <h2 class="form-title">Password reset complete</h2>
            <p>Your password has been set. You may go ahead and log in now.</p>

            <p class="loginhere">
                <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                <h2 class="form-title">Enter new password</h2>
                <div class="mb-3">
                    {{ form|crispy }}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Submit"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

        </div>
    </div>
</section>

{% endblock content %}

templates/accounts/password_reset_sent.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <h2 class="form-title">Password reset sent</h2>

            <p style="">We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

            <p style="">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

            <p class="loginhere mt-3">
                Go back to <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>

        </div>
    </div>
</section>

{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <h2 class="form-title">Create account</h2>
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
                {% endfor %}
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

            <p class="loginhere">
                Have already an account ? <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>
            <p class="loginhere">
                Forgot Password ? <a href="{% url 'accounts:reset_password' %}" class="loginhere-link">Reset Password</a>
            </p>
        </div>
    </div>
</section>

{% endblock content %}